FROM lukas3k11/simple-messenger-backend:base

# Install Xdebug 3
RUN pecl install xdebug && \
	echo 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so' >> /usr/local/etc/php/php.ini && \
	echo 'xdebug.mode=debug' >> /usr/local/etc/php/php.ini && \
	echo 'xdebug.client_host=host.docker.internal' >> /usr/local/etc/php/php.ini && \
	echo 'xdebug.client_port=9000' >> /usr/local/etc/php/php.ini && \
	echo 'xdebug.start_with_request=yes' >> /usr/local/etc/php/php.ini