FROM lukas3k11/simple-messenger-backend:base

COPY app ./app
COPY public ./public

RUN set -xe ; \
	composer install \
		--prefer-dist \
		--no-dev \
		--no-scripts \
		--no-progress \
		--optimize-autoloader \
		--no-ansi \
		--no-interaction