version: '3.7'

services:

  emqx:
    image: emqx/emqx:latest
    restart: "unless-stopped"
    ports:
      - "31002:31002"
      - "31003:31003"
      - "31004:18083"
    environment:
      - EMQX_LISTENER__TCP__EXTERNAL=31002
      - EMQX_LISTENER__WS__EXTERNAL=31003
    networks:
      local:

  postgres:
    image: postgres:latest
    restart: "unless-stopped"
    ports:
      - "31001:5432"
    env_file:
      - env/postgres.env
    environment:
      - TZ=UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      local:

  backend:
    image: lukas3k11/simple-messenger-backend:devel
    restart: "unless-stopped"
    ports:
      - "31000:80"
    env_file:
      - env/postgres.env
      - env/emqx.env
    environment:
      - TZ=UTC
    volumes:
      - ./../app:/var/www/app:rw
      - ./../public:/var/www/public:rw
      - ./../vendor:/var/www/vendor:rw
      - ./../composer.json:/var/www/composer.json:rw
      - ./../composer.lock:/var/www/composer.lock:rw
    depends_on:
      - postgres
      - emqx
    networks:
      local:

volumes:
  postgres_data:
    driver: local

networks:
  local: